### ISSUE TITLE
Alternative modes: git filter-branch, git replace

### ISSUE THREAD

**Issue by jnareb** [jayphelps/git-blame-someone-else#11]
Why does the app scripts around **interactive** rebase, instead of using [`git filter-branch`](https://www.kernel.org/pub/software/scm/git/docs/git-filter-branch.html) -- see the `--env-filter` example in docs?

For a less insane mode, what about using [`git replace`](https://www.kernel.org/pub/software/scm/git/docs/git-replace.html), to change the authorship (and committership) only in your own repository... well, at least until `refs/replaces/` gets propagated...

**Comment by jayphelps** [comment]
It uses interactive debase because this is a joke and it doesn't matter how it goes about it.
